# Generated by Django 5.2.17 on 2026-09-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Chocolate', 'Chocolate Obsession'), ('Cheesecake', 'Artisan Cheesecakes'), ('Fruit', 'Fresh Fruit & Berries'), ('Exotic', 'Exotic & Signature'), ('Eggless', '100% Eggless Specials')], default='Chocolate', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('badge', models.CharField(blank=True, help_text="e.g. Bestseller, Chef's Special, Trending, New", max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=38)),
                ('is_eggless', models.BooleanField(default=False)),
                ('weight_options', models.CharField(default='0.5 kg, 1 kg, 1.5 kg, 2 kg', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('delivery_date', models.CharField(blank=True, max_length=50)),
                ('delivery_slot', models.CharField(blank=True, max_length=50)),
                ('cake_message', models.CharField(blank=True, help_text='Custom greeting piped on cake', max_length=150)),
                ('items', models.TextField(help_text='Summary text of items')),
                ('items_json', models.TextField(default='[]', help_text='JSON formatted items for rich tracking')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='Razorpay (Online)', max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid (Verified)'), ('Failed', 'Failed')], default='Pending', max_length=30)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('order_status', models.CharField(choices=[('Order Placed', 'Order Placed'), ('Baking in Oven', 'Baking in Oven 👩\u200d🍳'), ('Decorating & Packing', 'Decorating & Packing 🎁'), ('Out for Delivery', 'Out for Delivery 🛵'), ('Delivered', 'Delivered 🎉'), ('Cancelled', 'Cancelled ❌')], default='Order Placed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
