# Generated by Django 5.2.17 on 2026-10-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.CharField(choices=[('Chocolate', 'Chocolate Obsession'), ('Cheesecake', 'Artisan Cheesecakes'), ('Fruit', 'Fresh Fruit & Berries'), ('Exotic', 'Exotic & Signature'), ('Eggless', '100% Eggless Specials'), ('Pastry', 'Artisan Pastries')], default='Chocolate', max_length=50),
        ),
    ]
